### ISSUE TITLE
Multichannel Version?

### ISSUE THREAD

**Issue by chris027** [pongasoft/vst-ab-switch#1]
Is there a way to make this AB Switch work with more than two channels? I'd love to use this with the 16 channel version of Blackhole.

Thanks so much for your hard work!

**Comment by ypujante** [comment]
There is a Rack Extension version (not VST) that supports 12 channels: https://pongasoft.com/rack-extensions/AB12Switch.html

github issues is not the right venue to ask this kind of questions. Check the [contacts](https://pongasoft.com/contact.html) page

Thank you
